namespace MudProxyViewer;

/// <summary>
/// Static lookup for MajorMUD ability IDs to human-readable names.
/// Used by detail dialogs to resolve Abil-N / AbilVal-N column pairs.
/// </summary>
public static class AbilityNames
{
    private static readonly Dictionary<int, string> _names = new()
    {
        { 1, "DamageNoMR" },
        { 2, "AC" },
        { 3, "Rcol" },
        { 4, "MaxDamage" },
        { 5, "Rfir" },
        { 6, "Enslave" },
        { 7, "DR" },
        { 8, "Drain" },
        { 9, "ShadowStealth" },
        { 10, "ACBlur" },
        { 11, "AlterEnergyLevel" },
        { 12, "Summon" },
        { 13, "Illu" },
        { 14, "RoomIllu" },
        { 15, "GypsyFortune" },
        { 16, "Rinaldo" },
        { 17, "DamageWithMR" },
        { 18, "Heal" },
        { 19, "Poison" },
        { 20, "CurePoison" },
        { 21, "ImmuPoison" },
        { 22, "Accuracy" },
        { 23, "AffectsUndead" },
        { 24, "Prev" },
        { 25, "Prgd" },
        { 26, "DetectMagic" },
        { 27, "Stealth" },
        { 28, "Magical" },
        { 29, "Punch" },
        { 30, "Kick" },
        { 31, "Bash" },
        { 32, "Smash" },
        { 33, "KillBlow" },
        { 34, "Dodge" },
        { 35, "JumpKick" },
        { 36, "MagicRes" },
        { 37, "Picklocks" },
        { 38, "Tracking" },
        { 39, "Thievery" },
        { 40, "FindTraps" },
        { 41, "DisarmTraps" },
        { 42, "LearnSpell" },
        { 43, "CastSpell" },
        { 44, "Intel" },
        { 45, "Willpower" },
        { 46, "Strength" },
        { 47, "Health" },
        { 48, "Agility" },
        { 49, "Charm" },
        { 50, "Quest1" },
        { 51, "AntiMagic" },
        { 52, "EvilInCombat" },
        { 53, "BlindingLight" },
        { 54, "TargetIllu" },
        { 55, "AlterLightDuration" },
        { 56, "RechargeItem" },
        { 57, "SeeHidden" },
        { 58, "Crits" },
        { 59, "ClassOK" },
        { 60, "Fear" },
        { 61, "AffectExit" },
        { 62, "AlterEvilChance" },
        { 63, "AlterExperience" },
        { 64, "AddCP" },
        { 65, "Rsto" },
        { 66, "Rlit" },
        { 67, "Quickness" },
        { 68, "Slowness" },
        { 69, "MaxMana" },
        { 70, "SpellCasting" },
        { 71, "Confusion" },
        { 72, "ShockShield" },
        { 73, "DispellMagic" },
        { 74, "HoldPerson" },
        { 75, "Paralyze" },
        { 76, "Mute" },
        { 77, "Perception" },
        { 78, "Animal" },
        { 79, "MageBind" },
        { 80, "AffectsAnimals" },
        { 81, "Freedom" },
        { 82, "Cursed" },
        { 83, "MajorCurse" },
        { 84, "RemoveCurse" },
        { 85, "Shatter" },
        { 86, "Quality" },
        { 87, "Speed" },
        { 88, "MaxHP" },
        { 89, "PunchAv" },
        { 90, "KickAv" },
        { 91, "JumpKAv" },
        { 92, "PunchDmg" },
        { 93, "KickDmg" },
        { 94, "JumpKDmg" },
        { 95, "Slay" },
        { 96, "Encum" },
        { 97, "Good" },
        { 98, "Evil" },
        { 99, "AlterDRByPercent" },
        { 100, "LoyalItem" },
        { 101, "ConfuseMsg" },
        { 102, "RaceStealth" },
        { 103, "ClassStealth" },
        { 104, "DefenseModifier" },
        { 105, "Accuracy2" },
        { 106, "Accuracy3" },
        { 107, "BlindUser" },
        { 108, "AffectsLiving" },
        { 109, "NonLiving" },
        { 110, "NotGood" },
        { 111, "NotEvil" },
        { 112, "Neutral" },
        { 113, "NotNeutral" },
        { 114, "PercentSpell" },
        { 115, "DescMsg" },
        { 116, "BSAccu" },
        { 117, "BSMinDmg" },
        { 118, "BSMaxDmg" },
        { 119, "DelAtMaint" },
        { 120, "StartMsg" },
        { 121, "Recharge" },
        { 122, "RemovesSpell" },
        { 123, "HPRegen" },
        { 124, "NegateAbility" },
        { 125, "IceSorceressQuest" },
        { 126, "GoodQuest" },
        { 127, "NeutralQuest" },
        { 128, "EvilQuest" },
        { 129, "DarkDruidQuest" },
        { 130, "BloodChampQuest" },
        { 131, "SheDragonQuest" },
        { 132, "WereratQuest" },
        { 133, "PhoenixQuest" },
        { 134, "DaoLordQuest" },
        { 135, "MinLevel" },
        { 136, "MaxLevel" },
        { 137, "ShockMsg" },
        { 138, "RoomVisible" },
        { 139, "SpellImmu" },
        { 140, "TeleportRoom" },
        { 141, "TeleportMap" },
        { 142, "HitMagic" },
        { 143, "ClearItem" },
        { 144, "NonMagicalSpell" },
        { 145, "ManaRegen" },
        { 146, "MonsGuards" },
        { 147, "ResistWater" },
        { 148, "Textblock" },
        { 149, "RemoveAtMaint" },
        { 150, "HealMana" },
        { 151, "EndCast" },
        { 152, "Rune" },
        { 153, "KillSpell" },
        { 154, "VisibleAtMaint" },
        { 155, "DeathText" },
        { 156, "QuestItem" },
        { 157, "ScatterItems" },
        { 158, "ReqToHit" },
        { 159, "KaiBind" },
        { 160, "GiveTempSpell" },
        { 161, "OpenDoor" },
        { 162, "Lore" },
        { 163, "SpellComponent" },
        { 164, "CastOnEndPercent" },
        { 165, "AlterSpellDamage" },
        { 166, "AlterSpellLength" },
        { 167, "UnequipItem" },
        { 168, "EquipItem" },
        { 169, "CannotWearLocation" },
        { 170, "Sleep" },
        { 171, "Invisibility" },
        { 172, "SeeInvisible" },
        { 173, "Scry" },
        { 174, "StealMana" },
        { 175, "StealHPToMP" },
        { 176, "StealMPToHP" },
        { 177, "SpellColours" },
        { 178, "ShadowForm" },
        { 179, "FindTrapsValue" },
        { 180, "PicklocksValue" },
        { 181, "GangHouseDeed" },
        { 182, "GangHouseTax" },
        { 183, "GangHouseItem" },
        { 184, "GangShopController" },
        { 185, "NoAttackIfItemNum" },
        { 186, "PerfectStealth" },
        { 187, "Meditate" },
        { 188, "UniquePerPool" },
        { 189, "WitchyBadgeQuest" },
        { 190, "NoStock" },
        { 191, "QuestFlag191" },
        { 192, "QuestFlag192" },
        { 193, "QuestFlag193" },
        { 194, "QuestFlag194" },
        { 195, "QuestFlag195" },
        { 196, "QuestFlag196" },
        { 197, "QuestFlag197" },
        { 198, "QuestFlag198" },
        { 199, "QuestFlag199" },
        { 200, "MandosQuest" },
        { 201, "VolumsQuest" },
        { 202, "CartographersQuest" },
        { 203, "LoremastersQuest" },
        { 204, "GuildmasterQuest" },
        { 205, "DarkbaneQuest" },
        { 206, "GrizzledRanger" },
        { 207, "AmazonHuntress" },
        { 208, "Conquest" },
        { 209, "Conquest2" },
        { 210, "TarlChain" },
        { 211, "MerchantCaptain" },
        { 212, "TrendelQuest" },
        { 213, "LucaProdigio" },
        { 214, "EtherealWatcher" },
        { 215, "KatoQuest" },
        { 216, "QuestFlag216" },
        { 217, "QuestFlag217" },
        { 218, "QuestFlag218" },
        { 219, "QuestFlag219" },
        { 220, "NagaQuest" },
        { 221, "DreadWraith" },
        { 222, "CourtesanQuest" },
        { 223, "QuestFlag223" },
        { 224, "QuestFlag224" },
        { 225, "QuestFlag225" },
        { 226, "QuestFlag226" },
        { 227, "QuestFlag227" },
        { 228, "QuestFlag228" },
        { 229, "QuestFlag229" },
        { 230, "QuestFlag230" },
        { 231, "QuestFlag231" },
        { 232, "QuestFlag232" },
        { 233, "QuestFlag233" },
        { 234, "QuestFlag234" },
        { 235, "QuestFlag235" },
        { 236, "QuestFlag236" },
        { 237, "QuestFlag237" },
        { 238, "QuestFlag238" },
        { 239, "QuestFlag239" },
        { 240, "QuestFlag240" },
        { 1001, "GrantThievery" },
        { 1002, "GrantTraps" },
        { 1003, "GrantPicklocks" },
        { 1004, "GrantTracking" },
        { 1103, "ShadowHome" }
    };

    public static string? GetName(int abilityId)
    {
        return _names.TryGetValue(abilityId, out var name) ? name : null;
    }

    public static List<(string Name, string Value)> ResolveAbilities(Dictionary<string, object?> data)
    {
        var result = new List<(string Name, string Value)>();

        for (int i = 0; i < 100; i++)
        {
            var abilKey = $"Abil-{i}";
            if (!data.TryGetValue(abilKey, out var abilObj))
                continue;

            int abilId = 0;
            if (abilObj is long l) abilId = (int)l;
            else if (abilObj is int ii) abilId = ii;
            else if (abilObj is decimal d) abilId = (int)d;
            else if (abilObj != null) int.TryParse(abilObj.ToString(), out abilId);

            if (abilId == 0)
                continue;

            var valKey = $"AbilVal-{i}";
            string value = "0";
            if (data.TryGetValue(valKey, out var valObj) && valObj != null)
                value = valObj.ToString() ?? "0";

            var name = GetName(abilId) ?? $"Unknown({abilId})";
            result.Add((name, value));
        }

        return result;
    }

    public static bool IsAbilityColumn(string key)
    {
        return key.StartsWith("Abil-", StringComparison.OrdinalIgnoreCase) ||
               key.StartsWith("AbilVal-", StringComparison.OrdinalIgnoreCase);
    }
}
